task :build do
  run "coffee -c --bare -o tmp lib"
  run "cat tmp/*.js > output/witopia.user.js"
  run "sed -n '1,/UserScript/p' output/witopia.user.js > output/witopia.meta.js"
end

task :watch do
  run "watchr witopia.watchr"
end

task :server do
  run "bpm preview --port 4020 &>/dev/null &"
end

def run(cmd)
  puts cmd
  system cmd
end

